# Generated by Django 4.2.2 on 2023-06-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifts', models.IntegerField()),
                ('tasks', models.FileField(upload_to='Media/')),
                ('tasks_links', models.FileField(upload_to='Media/')),
            ],
        ),
    ]
