# Generated by Django 4.2.2 on 2023-06-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProLine',
        ),
    ]
